### ISSUE TITLE
Background image doesn't 'cover' larger screens

### ISSUE THREAD

**Issue by thomasdashney** [thomasdashney/lost-cousins-website#1]
Currently using this CSS for the background image:

``` css
body {
    background: url(../img/man-tree-bg.jpg);
    background-position: center top;
    background-repeat: no-repeat;
    background-attachment: fixed;
}
```

but this doesn't resize the image to cover larger screens
